default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  user: postgres
  password: postgres  

development:
  <<: *default
  database: pedidos_app_development

test:
  <<: *default
  database: pedidos_app_test

production:
  <<: *default
  database: pedidos_app_production